build.gradle, src/main/java/umc/th/juinjang/apiPayload/ApiResponse.java, src/main/java/umc/th/juinjang/apiPayload/code/BaseCode.java, src/main/java/umc/th/juinjang/apiPayload/code/BaseErrorCode.java, src/main/java/umc/th/juinjang/apiPayload/code/ErrorReasonDTO.java, src/main/java/umc/th/juinjang/apiPayload/code/ReasonDTO.java, src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java, src/main/java/umc/th/juinjang/apiPayload/exception/ExceptionAdvice.java, src/main/java/umc/th/juinjang/apiPayload/exception/GeneralException.java, src/main/java/umc/th/juinjang/config/SwaggerConfig.java
**pr전에 오류가 없는지 다시 한 번 확인합시다~!
초기 설정 + swagger setting 등
=> [feat] 초기 설정

build.gradle, src/main/java/umc/th/juinjang/config/SwaggerConfig.java, src/main/java/umc/th/juinjang/controller/TestController.java
spring boot 3.대랑 호환 맞춤
https://colabear754.tistory.com/130
=> fix: swagger error

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/apiPayload/exception/handler/TempHandler.java, src/main/java/umc/th/juinjang/converter/TempConverter.java, src/main/java/umc/th/juinjang/model/dto/TempRequest.java, src/main/java/umc/th/juinjang/model/dto/TempResponse.java, src/main/java/umc/th/juinjang/model/entity/ChecklistAnswer.java, src/main/java/umc/th/juinjang/model/entity/ChecklistQuestion.java, src/main/java/umc/th/juinjang/model/entity/Image.java, src/main/java/umc/th/juinjang/model/entity/Limjang.java, src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java, src/main/java/umc/th/juinjang/model/entity/Member.java, src/main/java/umc/th/juinjang/model/entity/Record.java, src/main/java/umc/th/juinjang/model/entity/Report.java, src/main/java/umc/th/juinjang/model/entity/Scrap.java, src/main/java/umc/th/juinjang/model/entity/common/BaseEntity.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionCategory.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionType.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionVersion.java, src/main/java/umc/th/juinjang/model/entity/enums/LimjangPriceType.java, src/main/java/umc/th/juinjang/model/entity/enums/LimjangPropertyType.java, src/main/java/umc/th/juinjang/model/entity/enums/LimjangPurpose.java, src/main/java/umc/th/juinjang/model/entity/enums/MemberProvider.java, src/main/java/umc/th/juinjang/repository/LimjangRepository.java, src/main/java/umc/th/juinjang/service/TempService/TempCommandService.java, src/main/java/umc/th/juinjang/service/TempService/TempCommandServiceImpl.java, src/main/java/umc/th/juinjang/service/TempService/TempQueryService.java, src/main/java/umc/th/juinjang/service/TempService/TempQueryServiceImpl.java
빈 디렉토리 참을 수 없어서 깍두기로라도 임시 파일 만들었어요
=> [add: 파일들 추가]

build.gradle, src/main/java/umc/th/juinjang/config/SecurityConfig.java
spring security config 파일 세팅을 했답니다~
=> feat(#16) : security config ì작성

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/apiPayload/exception/handler/ChecklistHandler.java, src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/converter/checklist/ChecklistQuestionConverter.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistQuestionDTO.java, src/main/java/umc/th/juinjang/model/entity/ChecklistQuestion.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionCategory.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionType.java, src/main/java/umc/th/juinjang/model/entity/enums/ChecklistQuestionVersion.java, src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java, src/main/java/umc/th/juinjang/repository/checklist/ChecklistQuestionRepository.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
- 체크리스트 질문 목록 버전별 조회
- 스웨거 테스팅
- API 명세서 작성
version을 request param으로 주면 해당 버전에 맞는 체크리스트 질문들 모두 조회
=> [feat/#16] 체크리스트 질문 목록 버전별 조회

build.gradle, src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/config/SecurityConfig.java, src/main/java/umc/th/juinjang/jwt/JwtExceptionFilter.java, src/main/java/umc/th/juinjang/model/dto/auth/TokenDto.java, src/main/java/umc/th/juinjang/service/JwtService.java, src/main/java/umc/th/juinjang/service/auth/UserDetailServiceImpl.java
1. 발급, 유효성 확인 jwt service에 작성했습니다.
Oauth 작성 시 이용해주세요
=> [ADD] jwt 토큰 생성 발급 & 유효성 확인

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerConverter.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerRequestDTO.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerResponseDTO.java, src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
체크리스트 답변 저장
체크리스트 답변 조회
close #23
=> [feat/#23] 체크리스트 답변 저장 및 조회

src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/repository/checklist/ChecklistAnswerRepository.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
체크리스트 수정 로직 추가
프론트의 요청으로 체크리스트 수정 로직을 생성 로직에 넣어 변경하게 되었습니다 :)
close #27
=> [feat/#27] 체크리스트 수정 로직 추가

src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerAndReportResponseDTO.java, src/main/java/umc/th/juinjang/model/entity/Report.java, src/main/java/umc/th/juinjang/repository/checklist/ReportRepository.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
리포트 계산 로직 체크리스트 생성 또는 수정시에 추가
체크리스트를 생성하거나 수정할 때, 리포트를 계산해주는 로직을 추가했습니다.
=> [feat/#33] add report calc logic

.gitignore, src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/RecordController.java, src/main/java/umc/th/juinjang/converter/record/RecordConverter.java, src/main/java/umc/th/juinjang/model/dto/record/RecordRequestDTO.java, src/main/java/umc/th/juinjang/model/dto/record/RecordResponseDTO.java, src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java, src/main/java/umc/th/juinjang/repository/record/RecordRepository.java, src/main/java/umc/th/juinjang/service/recordService/RecordService.java
=> [feat/#39] 녹음 생성 삭제 구현

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java, src/main/java/umc/th/juinjang/controller/LimjangController.java, src/main/java/umc/th/juinjang/converter/limjang/LimjangPostConverter.java, src/main/java/umc/th/juinjang/converter/limjang/LimjangUpdateConverter.java, src/main/java/umc/th/juinjang/model/dto/limjang/LimjangUpdateRequestDTO.java, src/main/java/umc/th/juinjang/model/entity/Limjang.java, src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java, src/main/java/umc/th/juinjang/utils/LimjangUtil.java
임장 수정 구현
- 임장 수정 구현
- api 명세서 작성 완료
- 작성 형식 안맞았을 때 에러 던지는거(월세인 경우인데 가격 1개만 온경우.. 등등) Util로 옮김
=> [feat/#46] 임장 수정 구현

src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/model/dto/auth/LoginResponseDto.java, src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoOAuthToken.java, src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoUser.java, src/main/java/umc/th/juinjang/model/entity/Member.java, src/main/java/umc/th/juinjang/repository/limjang/MemberRepository.java, src/main/java/umc/th/juinjang/service/auth/KakaoOauth.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
카카오 OAuth 코드 생성 및 JWT 토큰 코드 연결 (테스트 전)
카카오 develop 생성 + OAuth 2.0 연결 + JWT 토큰 코드 연결
아직 테스트는 안해봐서 1차 코드임
=> feat(#16) : 카카오 oauth 코드 생성 (테스트 전)

src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerAndReportResponseDTO.java, src/main/java/umc/th/juinjang/model/dto/checklist/ReportResponseDTO.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
리포트 리턴값 변경
리포트 리턴값에 임장을 추가했어요!
=> fix: report return response

src/main/java/umc/th/juinjang/controller/RecordController.java, src/main/java/umc/th/juinjang/converter/record/RecordConverter.java, src/main/java/umc/th/juinjang/model/dto/record/RecordResponseDTO.java, src/main/java/umc/th/juinjang/model/entity/Record.java, src/main/java/umc/th/juinjang/repository/record/RecordRepository.java, src/main/java/umc/th/juinjang/service/recordService/RecordService.java
record 전체조회
record 3개 조회
record 전체조회
record 3개 조회
=> [feat/#55] record 조회

src/main/java/umc/th/juinjang/service/auth/KakaoOauth.java
=> fix(#16) : KakaoOauth 수정

src/main/java/umc/th/juinjang/service/auth/KakaoOauth.java
카카오 고쳐주기
아직 다 못고쳐서 카카오유저에 제대로 들어가게 추가적으로 해줘야해용
=> feat: kakao login

src/main/java/umc/th/juinjang/model/dto/auth/kakao/KakaoUser.java, src/main/java/umc/th/juinjang/model/entity/Member.java, src/main/java/umc/th/juinjang/service/auth/KakaoOauth.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
member entity nickname nullable 해제
=> fix(#16) : 카카오 로그인 수정

src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#16) : 카카오 로그인 member save 수정

src/main/java/umc/th/juinjang/config/SecurityConfig.java
=> fix: 시큐리티 수정

src/main/java/umc/th/juinjang/controller/ImageController.java, src/main/java/umc/th/juinjang/controller/LimjangController.java, src/main/java/umc/th/juinjang/controller/ScrapController.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
응답값 of-> onSuccess로 통일 
응답값 of-> onSuccess로 통일 
API 명세서 수정
=> [refactor/#67] 응답값 of-> onSuccess로 통일 

src/main/java/umc/th/juinjang/controller/ChecklistController.java, src/main/java/umc/th/juinjang/controller/RecordController.java
@PathVariable에 name 붙임
@PathVariable에 name 붙임
record, checklist Controller
=> [refactor/#67] : @PathVariable에 name 붙임

.github/workflows/gradle.yml
=> [refactor/#67] : gradle.yml 수정

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/config/SecurityConfig.java, src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/service/JwtService.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> feat(#16) : 액세스 토큰 재발급 api 구현

src/main/java/umc/th/juinjang/model/entity/Report.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandService.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
**pr전에 오류가 없는지 다시 한 번 확인합시다~!
1. pr 제목 형식 :  [type/#n]작업 내용 (n은 해당 작업 이슈번호)
예시 _: [fix/#6]로그인 에러 고치기
2. 작업한 내용 간단하게 해주고 상세한 설명, 캡쳐본 올려주면 됩니다.
3. 왼쪽에 태그 선택해주기(pr 대상, 작업 유형, 작업자)
4. 이 내용 지우고 ------------------ 아래 내용만 업로드해주면 됨
--------------------
이런 걸 했답니다
이 작업은 뭐에 대한거고 어쩌구저쩌구
=> refactor: refactored ChecklistCommandService.

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/MemberController.java, src/main/java/umc/th/juinjang/model/dto/member/MemberRequestDto.java, src/main/java/umc/th/juinjang/model/dto/member/MemberResponseDto.java, src/main/java/umc/th/juinjang/model/entity/Member.java, src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
=> feat(#83) : 닉네임 설정 및 수정 (memberId 기준)

src/main/java/umc/th/juinjang/controller/MemberController.java, src/main/java/umc/th/juinjang/model/dto/member/MemberResponseDto.java, src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
=> feat(#83) : 유저 조회 api 생성 중

src/main/java/umc/th/juinjang/config/SecurityConfig.java, src/main/java/umc/th/juinjang/controller/MemberController.java, src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
=> fix(#83) : 시큐리티 수정

src/main/java/umc/th/juinjang/controller/MemberController.java, src/main/java/umc/th/juinjang/service/MemberService/MemberService.java
=> feat(#83) : 유저 정보 조회

src/main/java/umc/th/juinjang/controller/RecordController.java, src/main/java/umc/th/juinjang/jwt/JwtAuthenticationFilter.java, src/main/java/umc/th/juinjang/model/dto/limjang/LimjangUpdateRequestDTO.java, src/main/java/umc/th/juinjang/model/dto/record/RecordRequestDTO.java, src/main/java/umc/th/juinjang/model/dto/record/RecordResponseDTO.java, src/main/java/umc/th/juinjang/model/entity/Limjang.java, src/main/java/umc/th/juinjang/model/entity/Record.java, src/main/java/umc/th/juinjang/repository/limjang/LimjangRepository.java, src/main/java/umc/th/juinjang/repository/record/RecordRepository.java, src/main/java/umc/th/juinjang/service/JwtService.java, src/main/java/umc/th/juinjang/service/recordService/RecordService.java
record api에 멤버 반영하고 메모, 녹음스크립트 dto 추가했습니다
=> [FEAT/#90] 토큰Member 인증 반영

src/main/java/umc/th/juinjang/config/SecurityConfig.java, src/main/java/umc/th/juinjang/jwt/JwtAuthenticationFilter.java, src/main/java/umc/th/juinjang/jwt/JwtExceptionFilter.java, src/main/java/umc/th/juinjang/service/JwtService.java
=> [FIX] jwt exception 처리

src/main/java/umc/th/juinjang/model/dto/auth/LoginResponseDto.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#16) : 로그인 response 닉네임 추가

src/main/java/umc/th/juinjang/controller/LimjangController.java, src/main/java/umc/th/juinjang/converter/limjang/LimjangDeleteConverter.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandService.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangCommandServiceImpl.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
**pr전에 오류가 없는지 다시 한 번 확인합시다~!
1. pr 제목 형식 :  [type/#n]작업 내용 (n은 해당 작업 이슈번호)
예시 _: [fix/#6]로그인 에러 고치기
2. 작업한 내용 간단하게 해주고 상세한 설명, 캡쳐본 올려주면 됩니다.
3. 왼쪽에 태그 선택해주기(pr 대상, 작업 유형, 작업자)
4. 이 내용 지우고 ------------------ 아래 내용만 업로드해주면 됨
--------------------
이런 걸 했답니다
이 작업은 뭐에 대한거고 어쩌구저쩌구
=> [feat] : detail fix,  delete 요청 방식 바꿈 #75

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/ImageController.java, src/main/java/umc/th/juinjang/controller/LimjangController.java, src/main/java/umc/th/juinjang/converter/limjang/LimjangMainListConverter.java, src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java, src/main/java/umc/th/juinjang/model/dto/limjang/LimjangMainViewListResponsetDTO.java, src/main/java/umc/th/juinjang/model/dto/limjang/LimjangTotalListResponseDTO.java, src/main/java/umc/th/juinjang/model/entity/enums/LimjangSort.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryService.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
임장 전체보기 api 수정
임장 전체보기 api 수정
- 스크랩-스크랩안된거 한번에 합침
- update, create, star에 따라 소팅하고 리턴
- 기존 응답값 포맷 약간 수정
=> [refactor/#102] 임장 전체보기 api 수정

src/main/java/umc/th/juinjang/controller/LimjangController.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
=> [comment/#102] 메인화면 api 로그 추가

build.gradle, src/main/java/umc/th/juinjang/JuinjangApplication.java, src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleClient.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/ApplePublicKeyResponse.java, src/main/java/umc/th/juinjang/service/JwtService.java, src/main/java/umc/th/juinjang/utils/ApplePublicKeyGenerator.java
애플로그인 public key 생성하는 부분 구현했습니다!
=> [feat] public key 생성 로직 구현

src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/jwt/JwtAuthenticationFilter.java, src/main/java/umc/th/juinjang/jwt/JwtExceptionFilter.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleClient.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleLoginRequestDto.java, src/main/java/umc/th/juinjang/service/JwtService.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> [feat/#113] 애플로그인

src/main/java/umc/th/juinjang/JuinjangApplication.java, src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java, src/main/java/umc/th/juinjang/model/entity/ChecklistAnswer.java
Consider defining a vean of type '~~.AppleClient' in your configuration.
에러 때문에 서버가 계속 재시작됨
=> feignClients bean주입 해결

src/main/java/umc/th/juinjang/JuinjangApplication.java
Consider defining a bean of type 'org.springframework.cloud.openfeign.FeignContext' in your configuration.
에러 해결
=> feignClients bean주입 해결2

src/main/java/umc/th/juinjang/config/SecurityConfig.java
=> fix(#124) : securityconfig 수정

.github/workflows/gradle.yml, build.gradle
=> [fix/#113] gradle file update

src/main/java/umc/th/juinjang/converter/checklist/ChecklistAnswerAndReportConverter.java, src/main/java/umc/th/juinjang/model/dto/checklist/ChecklistAnswerResponseDTO.java, src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistQueryServiceImpl.java
체크리스트 응답 구조 개선
프론트측에서 따로 category는 필요없다고 하시고, answerType은 필요하다고 하셔서 이 부분 반영
=> fix: checklist answer response fix

src/main/java/umc/th/juinjang/converter/limjang/LimjangDetailConverter.java, src/main/java/umc/th/juinjang/model/dto/limjang/LimjangDetailResponseDTO.java, src/main/java/umc/th/juinjang/model/dto/limjang/enums/LimjangCheckListVersionEnum.java, src/main/java/umc/th/juinjang/utils/LimjangUtil.java
임장 상세보기에 checkListVersion 추가
- 스웨거 테스트 완료
- 필드추가
- Enum의 문자열로 검색하도록 변경함
=> [feat/#157] 임장 상세보기에 checkListVersion 추가

src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
flush로 삭제 후 저장 로직 추가
flush로 삭제 후 저장 로직 추가
=> refactor: change delete and save logic

src/main/java/umc/th/juinjang/converter/limjang/LimjangTotalListConverter.java, src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepository.java, src/main/java/umc/th/juinjang/repository/limjang/LimjangQueryDslRepositoryImpl.java, src/main/java/umc/th/juinjang/service/LimjangService/LimjangQueryServiceImpl.java
임장 전체 조회 API 리팩토링 
- API 성능 최적화
- 지저분한 코드 정리
=> [refactor/#165] 임장 전체 조회 API 리팩토링 

src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
캘린더만 저장했을 때 categoryNum이 0으로 계산되어 totalRate를 0으로 나누게 되는 현상 제거
작업내용에 설명함.
=> fix: fix total rate divide by 0

src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
report 계산해서 score 타입 count가 0일때 rate값을 0.0으로 리턴하게 변경
=> fix: count가 0일때 0 리턴으로 변경

src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
=> fix: categoryRate가 0으로 평가될때 categoryCount를 하나 줄여주도록 fix

src/main/java/umc/th/juinjang/service/ChecklistService/ChecklistCommandServiceImpl.java
=> fix: categoryCount의 초깃값을 전체 카테고리 개수로 정의

.github/workflows/gradle.yml, build.gradle, src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleClient.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleClientSecretGenerator.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleOAuthProvider.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/ApplePrivateKeyGenerator.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleTokenRequest.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleTokenResponse.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
애플 탈퇴 구현
로컬에서 테스트가 안되는 관계로 추후 수정 예정
delete는 soft와 hard 중 논의 후 추가 예정
=> feat: 애플 탈퇴 구현

src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#164) : kakaoadminkey 타입 수정

src/main/java/umc/th/juinjang/model/entity/LimjangPrice.java
=> fix(#164) : entity 수정

src/main/java/umc/th/juinjang/apiPayload/code/status/SuccessStatus.java, src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> feat(#164) : oauth 탈퇴 response 수정

src/main/java/umc/th/juinjang/controller/OAuthController.java
=> fix(#164) : 탈퇴 url 수정

src/main/java/umc/th/juinjang/controller/OAuthController.java
=> fix(#164) : target_id 헤더 타입 변환

src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#164) : 로그 추가

src/main/java/umc/th/juinjang/controller/OAuthController.java
=> fix(#164) : 코드 수정

src/main/java/umc/th/juinjang/controller/OAuthController.java
=> fix(#164) : 코드 재수정

src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleClient.java, src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleOAuthProvider.java
=> fix(#164): /token 매개변수 형식 변경

src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleOAuthProvider.java
=> fix(#163): /token 로그 추가

src/main/java/umc/th/juinjang/model/dto/auth/apple/AppleOAuthProvider.java
=> fix(#164): client-id 변경

src/main/java/umc/th/juinjang/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/model/dto/auth/WithdrawReasonRequestDto.java, src/main/java/umc/th/juinjang/model/entity/Withdraw.java, src/main/java/umc/th/juinjang/model/entity/enums/WithdrawReason.java, src/main/java/umc/th/juinjang/repository/withdraw/WithdrawRepository.java, src/main/java/umc/th/juinjang/service/WithdrawService/WithdrawService.java
=> feat(#191) : 탈퇴 사유 기능 추가

src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#191) : 로그아웃 로그 추가

src/main/java/umc/th/juinjang/controller/OAuthController.java, src/main/java/umc/th/juinjang/service/auth/OAuthService.java
=> fix(#191) : 로그 수정

src/main/java/umc/th/juinjang/controller/OAuthController.java
=> fix(#191) : header key 이름 변경
